### ISSUE TITLE
How to skip the register, login screen?

### ISSUE THREAD

**Issue by jeonghyeon-net** [Arrowgene/Arrowgene.Ez2Off#3] opened 2018-08-04 19:02 UTC
Sorry to bad english OTZ

Halo!,

Now i can run ez2on r14, but i can't out the "make nickname" screen. just watch intro screen only.
(used r13 server. when the player clicked "make nickname button" and i catched the packet and see, it is null packet.)

how to i skip the login, register page?
I want to go select mode screen right away.

Thankz :D

**Comment by sebastian-heinz** [comment] 2018-08-05 03:17
1) The Ids between r13 and r14 are different, so a r14 client packet might not match the handler of the r13 server.
2) To Skip the "create nickname" you need to send a correct "character packet". If the client does not get character information it will assume you have no character and show the creation screen. If you send a character information the client will skip that and go into select mode.

**Comment by jeonghyeon-net** [comment] 2018-08-05 03:58
1. How to set R14 handler?
2. Where are "nickname" send packet code?

**Comment by sebastian-heinz** [comment] 2018-08-05 04:13
1. There is not a dedicated project to R14 yet, but you can experiment with r13.
Do this by looking into the packet handler definitions (https://github.com/Arrowgene/Arrowgene.Ez2Off/tree/master/Arrowgene.Ez2Off.Server.Reboot13/Packets) inside Login / World-Folder. 

A typical packet handler looks like this:

```
    public class LoginRequest : Handler<LoginServer>
    {
        public LoginRequest(LoginServer server) : base(server)
        {
        }

         // ID of packet that this handler should handle
        public override int Id => 0;

       // The handler method (access to packet data and client variables / state
        public override void Handle(EzClient client, EzPacket packet)
        {
            // Reading
            byte[] paramOne = packet.Data.ReadBytes(17);
            [...]
            // Writing
            IBuffer response = EzServer.Buffer.Provide();
            response.WriteByte(0);
            // Send to client with packet id of '0'
            Send(client, 0, response);
        }
}
```

You can modify existing handlers or create new ones.
If you create a new one it needs to be registered. In Login(https://github.com/Arrowgene/Arrowgene.Ez2Off/blob/master/Arrowgene.Ez2Off.Server.Reboot13/LoginServer.cs#L54) or World (https://github.com/Arrowgene/Arrowgene.Ez2Off/blob/master/Arrowgene.Ez2Off.Server.Reboot13/WorldServer.cs#L76) depending where it should happen.


2.
Character will be selected from DB here: https://github.com/Arrowgene/Arrowgene.Ez2Off/blob/master/Arrowgene.Ez2Off.Server.Reboot13/Packets/Login/LoginRequest.cs#L113

Character packet data will be send here : https://github.com/Arrowgene/Arrowgene.Ez2Off/blob/master/Arrowgene.Ez2Off.Server.Reboot13/Packets/Login/LoginRequest.cs#L141

Packet data will generally be build via "Builders" these are found inside the `Build`-Folder and help to create packets. The Character packet will be created here: https://github.com/Arrowgene/Arrowgene.Ez2Off/blob/master/Arrowgene.Ez2Off.Server.Reboot13/Packets/Builder/CharacterPacket.cs#L43

As you see if the Database returns `null` no character data will be send and the player is asked to create a new character.

A new character will be created here: https://github.com/Arrowgene/Arrowgene.Ez2Off/blob/master/Arrowgene.Ez2Off.Server.Reboot13/Packets/Login/CreateCharacter.cs#L50

After the character is created it is saved to DB, so the next time you login it will not be null and the screen will be skipped.

**Comment by gkfrnwkd** [comment] 2018-08-05 07:24
님 R13 방만들고 방설정할때 최대 인원수 바꾸는거 수정 가능한가요?

**Comment by miketestz** [comment] 2018-08-05 10:44
haha

**Comment by jeonghyeon-net** [comment] 2018-08-05 12:57
![image](https://user-images.githubusercontent.com/25793226/43686013-b3e95e64-98f9-11e8-87e7-3223f6447cbc.png)
I wrote the code like this. (EzServer.cs)

And waiting the terminal,
![image](https://user-images.githubusercontent.com/25793226/43686034-faaae6f6-98f9-11e8-92d4-9bfb3b5042a1.png)
▲ Connected the Server.

![image](https://user-images.githubusercontent.com/25793226/43686039-1812b548-98fa-11e8-86a0-2c162da3a55b.png)
![image](https://user-images.githubusercontent.com/25793226/43686044-22c211a0-98fa-11e8-85ca-415dc54ad596.png)
▲ Can't get the packet.


Where are is the problem? I pressed the create button but, nothing happened.
I guess can't get packet too. (something changed? r13 -> r14?)
Always, Thank you for your reply. :D

**Comment by sebastian-heinz** [comment] 2018-08-05 13:47
The client.Read()-method is responsible for reading the packet data (id, size, content) the problem is that r14 might have change the protocol so it can not read the bytes correctly, that is why no packet is created.

**Comment by jeonghyeon-net** [comment] 2018-08-05 14:08
So, what should i do? if you know it?

**Comment by sebastian-heinz** [comment] 2018-08-05 15:31
I haven't researched r14 enough to know the packet structure, sorry.
I'm focusing on R13 development, as some parts need to be fixed in this source.

1) Logic for changing master in room when somebody leaves.
2) Change Ready will not result in "WAITING"

If we have a perfect R13 source it will be easier to understand and develop R14.

**Comment by jeonghyeon-net** [comment] 2018-08-05 15:36
Ah! Okay Thank you :D
if you resolve the above two things, started develop the R14 server?

**Comment by ghost** [comment] 2018-08-05 15:43
r13 멀티 시스템 및 멀티 결과창 완벽하게 구현하고 r14로 넘어갑니다.

**Closed as completed** 2018-08-05 15:47 UTC
