### ISSUE TITLE
When someone die in multiplayer, game room stops sometime.

### ISSUE THREAD

**Issue by romanceformoon** [Arrowgene/Arrowgene.Ez2Off#5] opened 2018-09-26 16:53 UTC
What file is connected with this issue? I want to check that.

**Comment by sebastian-heinz** [comment] 2018-09-28 19:43
I think the issue is most likely in this file: https://github.com/Arrowgene/Arrowgene.Ez2Off/blob/master/Arrowgene.Ez2Off.Server.Reboot13/Packets/World/GameResult.cs

The problem I can see is that when a player disconnects during the match, a client has any error, nobody can progress. That is because the server will *wait* until all clients report they are finished.
In this line it will check if the room is finished https://github.com/Arrowgene/Arrowgene.Ez2Off/blob/master/Arrowgene.Ez2Off.Server.Reboot13/Packets/World/GameResult.cs#L140 and  The following packet will trigger the transition the the lobby screen:
https://github.com/Arrowgene/Arrowgene.Ez2Off/blob/master/Arrowgene.Ez2Off.Server.Reboot13/Packets/World/GameResult.cs#L156

Here is the part where the room checks if the player is finished: https://github.com/Arrowgene/Arrowgene.Ez2Off/blob/master/Arrowgene.Ez2Off.Server/Models/Room.cs#L160

Here is the line where the player `isPLaying` property will be set to `false` https://github.com/Arrowgene/Arrowgene.Ez2Off/blob/master/Arrowgene.Ez2Off.Server.Reboot13/Packets/World/GameResult.cs#L91

The problem is that the last player who finish, is responsible to trigger the server to execute the code to transit to the lobby screen.

As you can see this can fail in alot of ways and a better method need to be created.


1) You could use a timer that is song duration + 10 seconds, so it will always send the player to the lobby after THAT time, but this might trigger to early or to late (if all are gameover you don't want to wait)

2) You could send the packet to the client who just finished, this way you will ALWAYS go back to lobby, but the problem is that it will not be synchronised because people will be inside the lobby while others are playing.


The current flow is like this:
1) Whenever someone is game over or finish the song, it will trigger the GameResult.cs-code.
2) GameResult.cs will set `isPlaying` = `false`, then check if all players in the room are `isPlaying` = `false`
3) The last client will have `isPlaying` = `false` for everyone and execute the lobby move code.

If a player fails to set `isPlaying` = `false` you will be stuck in game (someone disconnects), if the last player fails to trigger the packet, everyone is also stuck in game.


I hope it can explain the problem.


I think the best solution would be, if a player finished he will start a check routine. The check routine would work as following:
1) GameResult.cs is triggered because one client finish or die
2) The client will start a method that will get a list of all people of the room
3) remove all offline / invalid clients from the list (if any)
4) check if the filtered clients are `isPlaying` = `false`
5.A) if all clients stopped playing, send lobby packet
5.B) if not all clients stopped playing, start step 2) again, after 10 seconds.

This will ensure that every client start checking for finished game, after he is done.
So if someone disconnect, the client don't relay on a single client to check.
If someone disconnect, the `isPlaying`-flag will be ignored because it these clients are filtered in step 3), this will ensure that the go to room packet is still send even clients are missing.

Of course if you know a better / less resource intensive solution please let me know.

**Comment by CHFreezer** [comment] 2018-09-29 17:03
Maybe I have fixed this problem
https://github.com/gameoldboy/Arrowgene.Ez2Off/blob/298044a54e9a878ebee75cc36f13c2a0ac7d2b96/Arrowgene.Ez2Off.Server.Reboot13/Packets/World/GameResult.cs#L153
https://github.com/gameoldboy/Arrowgene.Ez2Off/blob/298044a54e9a878ebee75cc36f13c2a0ac7d2b96/Arrowgene.Ez2Off.Server/Models/Room.cs#L50

**Comment by sebastian-heinz** [comment] 2018-10-02 15:41
Thank you for the updates, unfortunately I'm not able to verify or test any changes. But seeing you already put quite alot of work into it, I was wondering if you would like to have write access to this repo to help it out?

**Closed as completed** 2018-10-25 00:01 UTC
Labels: bug
